---
title: "Om KM 2021"
description: |
  Äntligen tid för KM! Läs först noggrannt på om vad som gäller för året stora FFF-händelse. OBS! Registrering börjar kl. 18:45 och start kl. 19:00. Se också till att ha minst en extravärja.
output:
  distill::distill_article:
    toc: true
    toc_depth: 2
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Datum

Se till att skriva in dom här datumen i din kalender:

-   16 september -- deltävling 1

-   30 september -- deltävling 2

-   21 oktober -- deltävling 3

-   11 november -- deltävling 4

-   25 november -- deltävling 5 då ny KM-segrare koras!!!

# Tider

**Registrering börjar kl. 18:45** då du skriver in dig i protokollet.

**Starten är kl. 19:00**. Som du förstår är det viktigt att passa tiden. Kommer du för sent får du dessväre inte delta.

# Regler och poängsystem

## Tävlingsformat

KM består av 5 stycken deltävlingar där deltagarna får poäng baserat på placering. Tävlingsformatet är alla möter alla i match om 5 stötar. Matcherna protokollförs och deltagarna ansvarar själva för att fylla i resultat samt att räkna samman antal segrar, utdelade och mottagna stötar samt stötindex.

## Poängsystem

Poängsumman från de 4 bästa placeringarna räknas samman och den fäktare med flest poäng vinner. Om flera fäktare har samma poäng vid sammanräkningen avgörs placeringen av bästa placeringen, dvs flest 1:a platser, flest 2:a platser, etc. Om även där lika avgörs placeringarna 1-3 genom omfäktning.

Och så här ser poänfördelningen ut:

+---------------+---------------+
| Placering     | Poäng         |
+===============+===============+
| 1             | 25            |
+---------------+---------------+
| 2             | 20            |
+---------------+---------------+
| 3             | 19            |
+---------------+---------------+
| 4             | 17            |
+---------------+---------------+
| 5             | 15            |
+---------------+---------------+
| 6             | 13            |
+---------------+---------------+
| 7             | 12            |
+---------------+---------------+
| 8             | 11            |
+---------------+---------------+
| 9             | 10            |
+---------------+---------------+
| 10            | 9             |
+---------------+---------------+
| 11            | 8             |
+---------------+---------------+
| 12            | 7             |
+---------------+---------------+
| 13            | 6             |
+---------------+---------------+
| 14            | 5             |
+---------------+---------------+
| 15            | 4             |
+---------------+---------------+
| 16            | 3             |
+---------------+---------------+
| 17            | 2             |
+---------------+---------------+
| 18 --         | 1             |
+---------------+---------------+
|               |               |
+---------------+---------------+

: Poängfördelning

# KM-historik

Om du vill läsa in dig på spännande KM-historik ber vi dig att titta på <https://km.lagerlof.org/stats/> . I år måste denna sajt ligga nere på grund av att redaktören är bannlyst och inte får arrangera tävlingar förr än tidigast den 1 juli 2022.
